config/routes.rb
Rails.application.routes.draw do
  devise_for :users

    get 'about' => 'welcome#about'

resources :wikipages

resources :charges, only: [:new, :create, :destroy]
resources :collaborators, only: [:create, :destroy]
resources :subscriptions

  authenticated :user do
    root 'welcome#index', as: :authenticated_root
  end
  root 'welcome#index'

end

app/models/wikipage.rb
class Wikipage < ActiveRecord::Base
#  before_create :default_wikipage_public

extend FriendlyId
friendly_id :title

belongs_to :user
has_many :collaborators
has_many :users, through: :collaborators

validates :title,
          uniqueness: { case_sensitive: false },
          length: { minimum: 3, maximum: 50 }

end

app/controllers/wikipages_controller.rb
class WikipagesController < ApplicationController
  include Pundit

rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  def index
    @wikipages = FilterWikis.call(current_user.role)
  end

  def show
    @wikipage = Wikipage.friendly.find(params[:id])
    @collaborator = @wikipage.users
  end

  def new
    @wikipage = Wikipage.new
    authorize @wikipage
  end

  def create
     @wikipage = current_user.wikipages.new(wikipage_params)
     authorize @wikipage

     if @wikipage.save
       flash[:notice] = "Entry was saved successfully."
       redirect_to @wikipage
     else
       flash.now[:alert] = "There was an error saving the entry. Please try again."
       render :new
     end
  end

  def edit
    @wikipage = Wikipage.friendly.find(params[:id])
    @users = User.where.not(id: current_user.id, role: 'standard')
    authorize @wikipage
  end

  def update
    @wikipage = Wikipage.friendly.find(params[:id])
    @wikipage.assign_attributes(wikipage_params)
    authorize @wikipage

    if @wikipage.save
      flash[:notice] = "Entry was updated successfully."
      redirect_to [@wikipage]
    else
      flash.now[:alert] = "There was an error saving the entry. Please try again."
      render :edit
    end
  end

  def destroy
    @wikipage = Wikipage.friendly.find(params[:id])
    authorize @wikipage

    if @wikipage.destroy
      flash[:notice] = "\"#{@wikipage.title}\" was deleted successfully."
      redirect_to wikipages_path
    else
      flash.now[:alert] = "There was an error deleting the wiki entry."
      render :show
    end
  end

  private

  def wikipage_params
    params.require(:wikipage).permit(:id, :title, :body, :public, user_ids: [])
  end

  def user_params
    params.require(:user).permit(:id, :role, :username)
  end

  def user_not_authorized
    flash[:warning] = "You are not authorized to perform this action."
    redirect_to(request.referrer || root_path)
  end


end

app/views/wikipages/edit.html.erb
<h1>Edit Entry</h1>

<div class="row">
  <div class="col-md-6">

    <%= form_for [@wikipage] do |f| %>

      <% if @wikipage.errors.any? %>
        <div class ="alert alert-danger">
          <h4><%= pluralize(wikipage.errors.count, "error") %>.</h4>
            <ul>
              <% wikipage.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
            </ul>
        </div>
      <% end %>

        <%= form_group_tag(@wikipage.errors[:title]) do %>
          <div class="form-group">
            <%= f.label :title %>
            <%= f.text_field :title, class: 'form-control', placeholder: "Enter entry title" %>
          </div>

          <div class="form-group">
            <%= f.label :body %>
            <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter entry body" %>
          </div>

          <% if current_user.admin? || current_user.premium? %>
            <div class="form-group">
              <%= f.check_box :public, {}, false, true%> Public
            </div>
          <% end %>

          <p><%= f.submit "Save", class: 'btn btn-success' %></p>

          <% if current_user.admin? || current_user.premium? %>
            <div class="form-group">
              <p><%= link_to "Delete Wiki", @wikipage, method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to delete this wiki?'} %></p>
            </div>
          <%end%>

          <% unless current_user.standard? %>
            <h4>Add collaborators </h4>
              <% @users.each do |user| %>
                <%= check_box_tag "wikipage[user_ids][]", user.id, @wikipage.users.include?(user) %>
                <%= label_tag dom_id(user), user.username %></li>
              <% end %>
          <% end %>
        <% end %>
    <%end%>
  </div>
  <div class="col-md-6">
    <div id="wiki-preview"></div>
  </div>
</div>


<div class="row">
  <div class="col-md-6">
    <h4>Simple Markdown:</h4>
      <table>
        <tr>
          <td> <i>Italics</i> </td>
          <td> *asterisks* or _underscores_ </td>
        </tr>
        <tr>
          <td> <b>Bold</b> </td>
          <td> **two asterisks** or __two underscores__ </td>
        </tr>
        <tr>
          <td> Paragraph break  &nbsp; &nbsp;  &nbsp;</td>
          <td> &lt;br> </td>
        </tr>
        <tr>
          <td> A <%= link_to "link", "http://daringfireball.net/projects/markdown/syntax", :title => "link name", :target =>"_blank" %> example.</td>
          <td> A [link](http://www.example.com/ "link name") example.</td>
        </tr>
      </table>
    <br>
    <p><%= link_to "Click here for the complete markdown reference.", "http://daringfireball.net/projects/markdown/syntax", :target =>"_blank" %></p>
    <br>
  </div>
</div>

app/views/wikipages/index.html.erb
<h1>Wiki Entries</h1>



<div class="row">
  <div class="col-md-8">
    <% @wikipages.each do |wikipage| %>
    <div class="media">
      <div class="media-body">
        <h4 class="media-heading">
          <%= link_to wikipage.title.split.map(&:capitalize).join(' '), wikipage %>
        </h4>
        <%= content_tag :span, 'Private', class: 'label label-primary' if wikipage.public? %>
    <% end %>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-8">
    <%= link_to "Create A New Wiki", new_wikipage_path, class: 'btn btn-lg btn-success center-block' %>
  </div>
</div>

app/views/wikipages/new.html.erb
<h1>New Wiki Page</h1>

<div class="row">
  <div class="col-md-6">

    <%= form_for [@wikipage] do |f| %>

      <% if @wikipage.errors.any? %>
        <div class ="alert alert-danger">
          <h4><%= pluralize(wikipage.errors.count, "error") %>.</h4>
            <ul>
              <% wikipage.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
            </ul>
        </div>
      <% end %>

        <%= form_group_tag(@wikipage.errors[:title]) do %>
          <div class="form-group">
            <%= f.label :title %>
            <%= f.text_field :title, class: 'form-control', placeholder: "Enter entry title" %>
          </div>

          <div class="form-group">
            <%= f.label :body %>
            <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter entry body" %>
          </div>

          <% if current_user.admin? || current_user.premium? %>
            <div class="form-group">
              <%= f.check_box :public, {}, false, true%> Public
            </div>
          <% end %>

          <p><%= f.submit "Save", class: 'btn btn-success' %></p>

          <% if current_user.admin? || current_user.premium? %>
            <div class="form-group">
              <p><%= link_to "Delete Wiki", @wikipage, method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to delete this wiki?'} %></p>
            </div>
          <% end %>
        <% end %>
    <%end%>
  </div>
  <div class="col-md-6">
    <h4><div id="wiki-preview-title"></div></h4>
    <div id="wiki-preview-body"></div>
  </div>
</div>


<div class="row">
  <div class="col-md-6">
    <h4>Simple Markdown:</h4>
      <table>
        <tr>
          <td> <i>Italics</i> </td>
          <td> *asterisks* or _underscores_ </td>
        </tr>
        <tr>
          <td> <b>Bold</b> </td>
          <td> **two asterisks** or __two underscores__ </td>
        </tr>
        <tr>
          <td> Paragraph break  &nbsp; &nbsp;  &nbsp;</td>
          <td> &lt;br> </td>
        </tr>
        <tr>
          <td> A <%= link_to "link", "http://daringfireball.net/projects/markdown/syntax", :title => "link name", :target =>"_blank" %> example.</td>
          <td> A [link](http://www.example.com/ "link name") example.</td>
        </tr>
      </table>
    <br>
    <p><%= link_to "Click here for the complete markdown reference.", "http://daringfireball.net/projects/markdown/syntax", :target =>"_blank" %></p>
    <br>
  </div>
</div>

app/views/wikipages/show.html.erb
<ol class="breadcrumb">
  <li><%= link_to "Home", root_path %></li>
  <li><%= link_to "Wikis", wikipages_path %></li>
  <li class="active"><%=@wikipage.title%></li>
</ol>


<h1><%= @wikipage.title.split.map(&:capitalize).join(' ') %></h1>

<div class="row">
  <div class="col-md-8">
    <p><%= markdown(@wikipage.body) %></p>
  </div>
</div>

<div class="col-md-4">
  <small> created <%= time_ago_in_words(@wikipage.created_at) %> ago by <%= @wikipage.user.username %></small>
</div>
<br>

<div class="col-md-12">
  <% if current_user.admin? || current_user.premium? %>
    <%= link_to "Edit", edit_wikipage_path(@wikipage), class: 'btn btn-success' %>
  <% end %>
</div>