config/routes.rb
Rails.application.routes.draw do
  devise_for :users

    get 'about' => 'welcome#about'

resources :wikipages

resources :charges, only: [:new, :create, :destroy]
resources :collaborators, only: [:create, :destroy]
resources :subscriptions

  authenticated :user do
    root 'welcome#index', as: :authenticated_root
  end
  root 'welcome#index'

end

app/models/charge.rb
class Charge < ActiveRecord::Base
  attr_accessor :stripe_card_token
  belongs_to :user
  validates_presence_of :plan_id
  validates_presence_of :email


  def save_with_payment
    if valid?
      customer = Stripe::Customer.create(description: email, plan: plan_id, card: stripe_card_token)
      self.stripe_customer_token = customer.id
      save!
    end
    rescue Stripe::InvalidRequestError => e
      logger.error "Stripe error while creating customer: #{e.message}"
      errors.add :base, "There was a problem with your credit card."
      false
  end

end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController


def new
end

def create
  @amount = 1500

  # Creates a Stripe Customer object, for associating with the charge
  customer = Stripe::Customer.create(
    email: current_user.email,
    card: params[:stripeToken]
    )

  charge = Stripe::Charge.create(
    customer: customer.id, # Note -- not user_id in app
    amount: @amount,
    description: "Premium Membership - #{current_user.email}",
    currency: 'usd'
    )

  if current_user.update(role: 'premium')
    flash[:success] = "Thank you for upgrading to Premium, #{current_user.email}!"
    redirect_to edit_user_registration_path
  else
    flash[:error] = "There was an error upgrading your account."
    redirect_to edit_user_registration_path
  end

  # Stripe will send back CardErrors, with friendly messages
  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_charge_path
end


  def destroy
    charge = current_user.charges.last
    refund = Stripe::Refund.create(
      charge: charge.stripe_charge_id,
      amount: charge.amount
    )

    if refund.status == 'succeeded'
      current_user.wikis.where(private: true).each do |wiki|
        wiki.update(private: false)
      end
      current_user.standard!
      flash[:notice] = 'Downgrade successful. Account status returned to Standard'
      redirect_to root_path
    end
  end

end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/views/charges/new.html.erb
<div class="row">
  <div class="col-md-12">
    <% if current_user.role == 'standard' %>
      <%= form_tag subscriptions_path do %>
        <h4>Sign up for a Premium Account!</h4>
        <h5>Create Private Wikis Only Other Premium Users Can See</h5>
        <p>For $15.00 a month you can create private wikis that only other premium users can see.</p>

        <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
            data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
            data-description="Blocipedia Premium Membership"
            data-amount="1500">
        </script>

<!-- If I decide to have two options?
            <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                  data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
                  data-description="Blocipedia Premium Subscription Membership"
                  data-amount="1500">
            </script>
-->
      <% end %>
    <% else %>
      <p>You are a premium user</p>
      <%= link_to 'Downgrade Account', charge_path(id:1), method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to cancel your Premium membership? Doing so makes all your private wikis go public.'} %>
    <% end %>

<br>

<div class="row">
  <div class="col-md-12 mt-10">
    <p><%= link_to "Back to Wikis", wikipages_path, class: 'btn btn' %></p>
  </div>
</div>