config/routes.rb
Rails.application.routes.draw do
  devise_for :users

    get 'about' => 'welcome#about'

resources :wikipages

resources :charges, only: [:new, :create, :destroy]
resources :collaborators, only: [:create, :destroy]
resources :subscriptions

  authenticated :user do
    root 'welcome#index', as: :authenticated_root
  end
  root 'welcome#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Wiki</title>
  <meta name="viewport" content="width=depth-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "https://js.stripe.com/v1/", "application" %>
  <%= javascript_include_tag "https://cdnjs.cloudflare.com/ajax/libs/showdown/1.4.2/showdown.min.js" %>
  <%= csrf_meta_tags %>
</head>

<body>
  <div class="container">
    <ul class="nav nav-tabs">
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "Wikis", wikipages_path %></li>
      <li><%= link_to "About", about_path %></li>

      <div class="pull-right user-info">
        <% if user_signed_in? %>
          Signed in as:
          <div class="avatar"><%= image_tag avatar_url(current_user) %></div>
          <strong><%= current_user.username %></strong> |
          <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> -
          <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
        <% else %>
          <%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link'  %> -
          <%= link_to "Sign In", new_user_session_path, :class => 'navbar-link'  %>
        <% end %>
      </div>
    </ul>

    <% if flash[:notice] %>
      <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:notice] %>
      </div>
    <% elsif flash.now[:alert] %>
      <div class="alert alert-danger">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash.now[:alert] %>
      </div>
    <% elsif flash[:alert] %>
      <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:alert] %>
      </div>
    <% end %>


    <%= yield %>


  </div>

</body>
</html>